# Workflow for deploying a Next.js site to GitHub Pages (with strict public npm enforcement)
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean npm configuration
        run: |
          # Remove all possible registry configurations
          rm -f .npmrc
          rm -f ~/.npmrc
          npm config delete registry
          npm config delete @myscope:registry
          npm config delete //nexus-registry.example.com/:_authToken
          echo "Cleaned all npm configurations"

      - name: Verify npm registry
        run: |
          npm config get registry
          if [ "$(npm config get registry)" != "https://registry.npmjs.org/" ]; then
            echo "ERROR: Registry not set correctly"
            exit 1
          fi

      - name: Setup Node.js with public registry
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          registry-url: "https://registry.npmjs.org/"
          always-auth: false  # Disable authentication

      - name: Install dependencies (with registry verification)
        run: |
          echo "Current registry: $(npm config get registry)"
          npm install --loglevel verbose
          # Verify no private packages
          if grep -q '"@.*":' package-lock.json; then
            echo "ERROR: Private scoped packages detected"
            exit 1
          fi

      - name: Build with Next.js
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
